"""sprint 1 - cadastros e ativos

Revision ID: 13ade34ba8a3
Revises: 8b17f25f113a
Create Date: 2026-09-27 15:53:04.165757

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ade34ba8a3'
down_revision: str | None = '8b17f25f113a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('vida_util_meses', sa.Integer(), nullable=False),
    sa.Column('tipo_aplicavel', sa.String(length=10), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo_aplicavel IN ('HARDWARE', 'SOFTWARE')", name='ck_categoria_tipo_aplicavel'),
    sa.CheckConstraint('vida_util_meses > 0', name='ck_categoria_vida_util_positiva'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=160), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('contato', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('sigla', sa.String(length=12), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("perfil IN ('ADMIN', 'OPERADOR', 'GESTOR', 'AUDITOR')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('entidade', sa.String(length=80), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('regra_violada', sa.String(length=20), nullable=True),
    sa.Column('detalhe', sa.JSON(), nullable=True),
    sa.Column('carimbo', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_importacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('total_processado', sa.Integer(), nullable=False),
    sa.Column('total_aceito', sa.Integer(), nullable=False),
    sa.Column('total_rejeitado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('localizacao', sa.String(length=120), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=80), nullable=True),
    sa.Column('chave_licenca', sa.String(length=200), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=False),
    sa.Column('valor_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vida_util_meses', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('localizacao', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('lote_importacao_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(tipo = 'HARDWARE' AND numero_serie IS NOT NULL) OR (tipo = 'SOFTWARE' AND chave_licenca IS NOT NULL)", name='ck_ativo_identificador'),
    sa.CheckConstraint("status IN ('ATIVO', 'EM_MANUTENCAO', 'BAIXADO')", name='ck_ativo_status'),
    sa.CheckConstraint("tipo IN ('HARDWARE', 'SOFTWARE')", name='ck_ativo_tipo'),
    sa.CheckConstraint('length(nome) >= 3', name='ck_ativo_nome_minimo'),
    sa.CheckConstraint('valor_compra > 0', name='ck_ativo_valor_positivo'),
    sa.CheckConstraint('vida_util_meses > 0', name='ck_ativo_vida_util_positiva'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['lote_importacao_id'], ['lote_importacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index('ix_ativo_categoria_id', 'ativo', ['categoria_id'], unique=False)
    op.create_index('ix_ativo_data_aquisicao', 'ativo', ['data_aquisicao'], unique=False)
    op.create_index('ix_ativo_fornecedor_id', 'ativo', ['fornecedor_id'], unique=False)
    op.create_index('ix_ativo_status', 'ativo', ['status'], unique=False)
    op.create_table('erro_importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('numero_linha', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=False),
    sa.Column('valor_recebido', sa.String(length=255), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_importacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erro_importacao')
    op.drop_index('ix_ativo_status', table_name='ativo')
    op.drop_index('ix_ativo_fornecedor_id', table_name='ativo')
    op.drop_index('ix_ativo_data_aquisicao', table_name='ativo')
    op.drop_index('ix_ativo_categoria_id', table_name='ativo')
    op.drop_table('ativo')
    op.drop_table('responsavel')
    op.drop_table('lote_importacao')
    op.drop_table('audit_log')
    op.drop_table('usuario')
    op.drop_table('setor')
    op.drop_table('fornecedor')
    op.drop_table('categoria')
    # ### end Alembic commands ###
