"""sprint 5 risco

Revision ID: a7c1e5d90b21
Revises: f5f9acc0de7b
Create Date: 2026-10-03 00:06:21.142202

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c1e5d90b21'
down_revision: str | None = 'f5f9acc0de7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('probabilidade', sa.Integer(), nullable=False),
    sa.Column('impacto', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), sa.Computed('probabilidade * impacto', persisted=True), nullable=False),
    sa.Column('resposta', sa.String(length=20), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gatilho', sa.String(length=255), nullable=True),
    sa.Column('data_revisao', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categoria IN ('OPERACIONAL', 'FINANCEIRO', 'LEGAL', 'SEGURANCA', 'CONTINUIDADE')", name='ck_risco_categoria'),
    sa.CheckConstraint("resposta IN ('ACEITAR', 'MITIGAR', 'TRANSFERIR', 'EVITAR')", name='ck_risco_resposta'),
    sa.CheckConstraint("status IN ('ABERTO', 'EM_TRATAMENTO', 'ENCERRADO')", name='ck_risco_status'),
    sa.CheckConstraint('impacto BETWEEN 1 AND 5', name='ck_risco_impacto'),
    sa.CheckConstraint('length(titulo) >= 3', name='ck_risco_titulo_minimo'),
    sa.CheckConstraint('probabilidade BETWEEN 1 AND 5', name='ck_risco_probabilidade'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risco_score', 'risco', ['score'], unique=False)
    op.create_index('ix_risco_status', 'risco', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risco_status', table_name='risco')
    op.drop_index('ix_risco_score', table_name='risco')
    op.drop_table('risco')
    # ### end Alembic commands ###
