"""sprint 5 fornecedor avaliacao

Revision ID: b3d8f2a61c47
Revises: a7c1e5d90b21
Create Date: 2026-10-03 00:15:27.618132

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d8f2a61c47'
down_revision: str | None = 'a7c1e5d90b21'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('criterio', sa.String(length=80), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nota', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nota BETWEEN 0 AND 10', name='ck_avaliacao_nota'),
    sa.CheckConstraint('peso > 0 AND peso <= 100', name='ck_avaliacao_peso'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_avaliacao_fornecedor', 'fornecedor_avaliacao', ['fornecedor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_avaliacao_fornecedor', table_name='fornecedor_avaliacao')
    op.drop_table('fornecedor_avaliacao')
    # ### end Alembic commands ###
