"""sprint 2 - historico de transferencia

Revision ID: c8365ce7e5e4
Revises: 13ade34ba8a3
Create Date: 2026-09-29 22:48:00.796063

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8365ce7e5e4'
down_revision: str | None = '13ade34ba8a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Trigger de imutabilidade (BR-011, BR-025, ADR-005) — cópia congelada da DDL de
# app/models/historico.py (migração não importa modelo, que muda ao longo do tempo).
FUNCAO_PERMITIR_APENAS_ENCERRAMENTO = """
CREATE OR REPLACE FUNCTION permitir_apenas_encerramento() RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Vínculo histórico não pode ser excluído (BR-025)';
  END IF;
  IF OLD.data_fim IS NOT NULL THEN
    RAISE EXCEPTION 'Vínculo já encerrado é imutável (BR-011)';
  END IF;
  IF NEW.id                IS DISTINCT FROM OLD.id
  OR NEW.ativo_id          IS DISTINCT FROM OLD.ativo_id
  OR NEW.responsavel_id    IS DISTINCT FROM OLD.responsavel_id
  OR NEW.setor_id          IS DISTINCT FROM OLD.setor_id
  OR NEW.data_inicio       IS DISTINCT FROM OLD.data_inicio
  OR NEW.motivo            IS DISTINCT FROM OLD.motivo
  OR NEW.registrado_por_id IS DISTINCT FROM OLD.registrado_por_id
  OR NEW.data_source       IS DISTINCT FROM OLD.data_source
  OR NEW.criado_em         IS DISTINCT FROM OLD.criado_em THEN
    RAISE EXCEPTION 'Somente data_fim pode ser preenchida (BR-011)';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

TRIGGER_HISTORICO_IMUTAVEL = """
CREATE TRIGGER tg_historico_imutavel
  BEFORE UPDATE OR DELETE ON historico_transferencia
  FOR EACH ROW EXECUTE FUNCTION permitir_apenas_encerramento();
"""


def _postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('data_fim IS NULL OR data_fim >= data_inicio', name='ck_historico_periodo_valido'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_vinculo_aberto', 'historico_transferencia', ['ativo_id'], unique=True, postgresql_where=sa.text('data_fim IS NULL'), sqlite_where=sa.text('data_fim IS NULL'))
    # ### end Alembic commands ###
    if _postgres():
        op.execute(FUNCAO_PERMITIR_APENAS_ENCERRAMENTO)
        op.execute(TRIGGER_HISTORICO_IMUTAVEL)


def downgrade() -> None:
    if _postgres():
        op.execute("DROP TRIGGER IF EXISTS tg_historico_imutavel ON historico_transferencia")
        op.execute("DROP FUNCTION IF EXISTS permitir_apenas_encerramento()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_vinculo_aberto', table_name='historico_transferencia', postgresql_where=sa.text('data_fim IS NULL'), sqlite_where=sa.text('data_fim IS NULL'))
    op.drop_table('historico_transferencia')
    # ### end Alembic commands ###
