"""sprint 5 recomendacao e evidencia

Revision ID: c9e4a7d25f83
Revises: b3d8f2a61c47
Create Date: 2026-10-03 00:26:23.205759

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e4a7d25f83'
down_revision: str | None = 'b3d8f2a61c47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('contexto', sa.String(length=2000), nullable=False),
    sa.Column('recomendacao', sa.String(length=2000), nullable=False),
    sa.Column('alternativas', sa.String(length=2000), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSTA', 'APROVADA', 'REJEITADA', 'IMPLEMENTADA')", name='ck_recomendacao_status'),
    sa.CheckConstraint('length(titulo) >= 3', name='ck_recomendacao_titulo_minimo'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recomendacao_status', 'recomendacao', ['status'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recomendacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.CheckConstraint("tipo IN ('CENARIO', 'INDICADOR', 'PREMISSA') OR referencia_id IS NOT NULL", name='ck_evidencia_referencia'),
    sa.CheckConstraint("tipo IN ('INDICADOR', 'RISCO', 'ATIVO', 'LICENCA', 'SCORECARD', 'CENARIO', 'PREMISSA')", name='ck_evidencia_tipo'),
    sa.CheckConstraint("tipo NOT IN ('CENARIO', 'INDICADOR', 'PREMISSA') OR (descricao IS NOT NULL AND length(descricao) >= 3)", name='ck_evidencia_descricao'),
    sa.ForeignKeyConstraint(['recomendacao_id'], ['recomendacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidencia_recomendacao', 'evidencia', ['recomendacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidencia_recomendacao', table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index('ix_recomendacao_status', table_name='recomendacao')
    op.drop_table('recomendacao')
    # ### end Alembic commands ###
