"""sprint 3 baixa de ativo

Revision ID: ee62f9bcb421
Revises: 25b1f6d20128
Create Date: 2026-10-02 11:21:22.914016

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee62f9bcb421'
down_revision: str | None = '25b1f6d20128'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Trigger de imutabilidade de baixa_ativo (BR-025, NFR-AUD-01, ADR-005) — cópia congelada da DDL
# de app/models/baixa.py. A função bloquear_mutacao() já existe (migração 25b1f6d20128, que a
# criou para audit_log): CREATE OR REPLACE a reaplica sem erro, e o downgrade NÃO a remove,
# porque audit_log continua dependendo dela (docs/modelo-de-dados/invariantes.md).
FUNCAO_BLOQUEAR_MUTACAO = """
CREATE OR REPLACE FUNCTION bloquear_mutacao() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Registro histórico é imutável (NFR-AUD-01)';
END;
$$ LANGUAGE plpgsql;
"""

TRIGGER_BAIXA_IMUTAVEL = """
CREATE TRIGGER tg_baixa_imutavel
  BEFORE UPDATE OR DELETE ON baixa_ativo
  FOR EACH ROW EXECUTE FUNCTION bloquear_mutacao();
"""


def _postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baixa_ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('justificativa', sa.String(length=500), nullable=True),
    sa.Column('data_baixa', sa.Date(), nullable=False),
    sa.Column('destinacao', sa.String(length=30), nullable=False),
    sa.Column('valor_residual_baixa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("destinacao IN ('RECICLAGEM_CERTIFICADA', 'DOACAO', 'DEVOLUCAO_FORNECEDOR', 'VENDA', 'DESCARTE')", name='ck_baixa_destinacao'),
    sa.CheckConstraint("motivo <> 'OUTRO' OR (justificativa IS NOT NULL AND length(justificativa) >= 10)", name='ck_baixa_justificativa'),
    sa.CheckConstraint("motivo IN ('OBSOLESCENCIA', 'DEFEITO', 'FURTO_ROUBO', 'FIM_VIDA_UTIL', 'OUTRO')", name='ck_baixa_motivo'),
    sa.CheckConstraint('valor_residual_baixa >= 0', name='ck_baixa_residual_nao_negativo'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id')
    )
    # ### end Alembic commands ###
    if _postgres():
        op.execute(FUNCAO_BLOQUEAR_MUTACAO)
        op.execute(TRIGGER_BAIXA_IMUTAVEL)


def downgrade() -> None:
    if _postgres():
        op.execute("DROP TRIGGER IF EXISTS tg_baixa_imutavel ON baixa_ativo")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baixa_ativo')
    # ### end Alembic commands ###
