"""sprint 3 licenca e vinculo

Revision ID: f5f9acc0de7b
Revises: ee62f9bcb421
Create Date: 2026-10-02 11:30:53.107809

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f9acc0de7b'
down_revision: str | None = 'ee62f9bcb421'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('software', sa.String(length=120), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('chave_licenca', sa.String(length=200), nullable=False),
    sa.Column('quantidade_contratada', sa.Integer(), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_expiracao', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tipo_licenciamento', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.CheckConstraint("(tipo_licenciamento = 'PERPETUA' AND ativo_id IS NOT NULL AND software IS NULL AND valor_total IS NULL) OR (tipo_licenciamento = 'SUBSCRICAO' AND ativo_id IS NULL AND software IS NOT NULL AND valor_total IS NOT NULL) OR (tipo_licenciamento = 'OEM' AND ativo_id IS NULL AND software IS NOT NULL AND valor_total IS NULL)", name='ck_licenca_tipo'),
    sa.CheckConstraint("tipo_licenciamento IN ('PERPETUA', 'SUBSCRICAO', 'OEM')", name='ck_licenca_tipo_licenciamento'),
    sa.CheckConstraint('data_expiracao > data_inicio_vigencia', name='ck_licenca_vigencia'),
    sa.CheckConstraint('quantidade_contratada >= 1', name='ck_licenca_quantidade_minima'),
    sa.CheckConstraint('valor_total IS NULL OR valor_total > 0', name='ck_licenca_valor_positivo'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenca_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licenca_id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('data_vinculo', sa.Date(), nullable=False),
    sa.Column('ativo_vinculo', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['licenca_id'], ['licenca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_licenca_ativo', 'licenca_vinculo', ['licenca_id', 'ativo_id'], unique=True, postgresql_where=sa.text('ativo_vinculo = true'), sqlite_where=sa.text('ativo_vinculo = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_licenca_ativo', table_name='licenca_vinculo', postgresql_where=sa.text('ativo_vinculo = true'), sqlite_where=sa.text('ativo_vinculo = 1'))
    op.drop_table('licenca_vinculo')
    op.drop_table('licenca')
    # ### end Alembic commands ###
